fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
name: Production
type: Environment
